sudo: required
services:
  - docker

before_install:
  - docker build -t likcu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true likcu/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-213051230259"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"




  